# ================================
# PERFIL PROD - Produccion / Railway
# Base PostgreSQL
# ================================

server.port=${PORT:8080}

# PostgreSQL en Railway
spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.open-in-view=false

# H2 Console desactivada en produccion
spring.h2.console.enabled=false